name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: development

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
       username: ahrechanychenko
       password: ${{ secrets.DOCKERHUB_SECRET }}
    - name: Build the Docker image
      run: export VERSION=$(jq -r .version package.json) && docker build . --file Dockerfile --tag ahrechanychenko/node-test-app:$VERSION.$GITHUB_RUN_ID
    - name: Docker push
      run: export VERSION=$(jq -r .version package.json) && docker push ahrechanychenko/node-test-app:$VERSION.$GITHUB_RUN_ID

  helm:

    runs-on: self-hosted
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: check k8s
        run: export KUBECONFIG=/Users/ahrechanychenko/.kube/config && kubectl cluster-info
      - name: check k8s
        run: export VERSION=$(jq -r .version package.json) && export KUBECONFIG=/Users/ahrechanychenko/.kube/config && helm upgrade first-try --set image_tag=$VERSION.$GITHUB_RUN_ID /Users/ahrechanychenko/Documents/DevOps01/k8s/lesson6/nodejs-app-chart -n devops01
